ignore:
  - "examples"
  - "experiments"
codecov:
    # Avoid "Missing base report"
    # https://docs.codecov.io/docs/comparing-commits
    allow_coverage_offsets: true
    require_ci_to_pass: false
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # only post the comment if coverage changes
